name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install and build
        run: |
          yarn
          yarn postinstall
          yarn package

      - name: Publish the app and generate a release based on semantic commit
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/*.dmg
            ./release/*.zip
          tag_name: ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
